version: "3.8"
services:
  bot:
    container_name: the_fool
    environment:
      - DISCORD_BOT_TOKEN=
      - DISCORD_GEMINI_CHANNEL_ID=
      - QBITTORRENT_HOST=
      - QBITTORRENT_PORT=
      - QBITTORRENT_USERNAME=
      - QBITTORRENT_PASSWORD=
      - ARIA2_HOST=
      - ARIA2_PORT=
      - ARIA2_SECRET=
    build: .
    volumes:
      - type: bind
        source: ./cookies.json
        target: /app/cookies.json
    restart: unless-stopped
